### ISSUE TITLE
Confusing usage of the word node when you mean node coordinates

### ISSUE THREAD

**Issue by DanielPerezJensen** [DanielPerezJensen/mapc-uva#11]
In graph.py, we use the word nodes in function names such as:

`
def get_local_nodes()
def get_new_nodes()
`

Even though the function returns node coordinates, and not the actual node objects. The name is not congruent with the docstring.

Maybe change the name, or make it return Nodes (I prefer the second option).

**Comment by dorian4840** [comment]
The documentation for the functions in graph.py has been extended and improved. Every function now clearly states what it returns.
