### ISSUE TITLE
Need function that returns a node or None depending on if node exists in graph

### ISSUE THREAD

**Issue by DanielPerezJensen** [DanielPerezJensen/mapc-uva#12]
Currently if we want to retrieve a node that may or may not exist yet in the graph we have to do this:

```python
try:
    node = self.graph.nodes[(x, y)]
    # do whatever with node
```

Wouldn't it be better to have a function that simply either returns the node or None depending on if the node is already in the graph?

**Comment by dorian4840** [comment]
Create a function graph.get_node(coordinates), that returns the node on the given coordinate, if it exists. The function is in the mapper branch
