### ISSUE TITLE
Agents need to be able to navigate with blocks attached to them.

### ISSUE THREAD

**Issue by lucweytingh** [DanielPerezJensen/mapc-uva#36]
As of now, agents do not know how to path-find with blocks attached. It would be great if there is a general solution to this problem.

**Comment by s1l3n0** [comment]
A rough solution would be to make the planning on a coarser map, decreasing
the definition so that an agent plus blocks count as a full position.

Il ven 22 mag 2020, 09:36 Luc Weytingh <notifications@github.com> ha
scritto:

**Comment by lucweytingh** [comment]
> A rough solution would be to make the planning on a coarser map, decreasing the definition so that an agent plus blocks count as a full position.

I agree with this theoretically. The only downside to this solution, however, is that we would have to search the entire map for obstacles and expand the obstacles in the direction of attached blocks for an agent. This could be computationally intensive. 

Another possibility could be to only path plan normally, but when computing the transition costs to a certain node, the nodes relative to that node corresponding with the relative block attachments could be checked.

i.e. (simplified) 
```python
def transition_cost(from, to):
    for node in [from, to] + relative_attached:
        if node is obstacle:
            return inf

    return 1
```

**Comment by lucweytingh** [comment]
As it turns out, checking the neighbours for every possible next node is very computationally intensive too. Perhaps I could instead only check the final path for 'if it is possible' and turn if it is not.

**Comment by s1l3n0** [comment]
Perhaps I was not clear,

if you transform all your maps by grouping e.g. 9 cells in one cell.

o = empty,
O = obstacle
X = agent
B = block

O o o
o o o    ==> O
o o O

o o o
B X B  ===> X
o o o

you can plan in the new map as it was just a simple agent.
there will be configurations possible which are certainly lost, but at
least if there are solutions they will be given tractably.
or am I losing part of the problem?

**Comment by DanielPerezJensen** [comment]
This may also make it harder to merge the Graphs as @dorian4840 is working on, since each agent with blocks attached must have it's own graph where these issues are taken into account.

**Comment by s1l3n0** [comment]
perhaps you could try an hybrid solution. e.g. by constructing two graphs:
one well-defined, one rough (compressed).
[which reminds by the way how humans remember locations.
https://www.researchgate.net/publication/200827817_Cognitive_Maps_Cognitive_Collages_and_Spatial_Mental_Models
]

**Comment by lucweytingh** [comment]
I understand what you meant, this solution somewhat looks like what you suggested:  https://harablog.wordpress.com/2009/01/29/clearance-based-pathfinding/.

**Comment by s1l3n0** [comment]
Yes, it is practically the same idea.

**Comment by s1l3n0** [comment]
A interesting difference one can notice is that the size of the elements in
the game they considered are fixed while in your case you can change it.
so for instance, if you don't find a path with a cell of 9, you can try to
find it with a cell of 4.

e.g.
from cell of 9 (max 8 blocks?)
o B o
o X B ===> X
o o o

to cell of 4 (max 3 blocks?)
B o
X B  ===> X
