### ISSUE TITLE
Use Tobias Albrecht's idea for creating proper amount of agents

### ISSUE THREAD

**Issue by DanielPerezJensen** [DanielPerezJensen/mapc-uva#40]
> I think I would always create enough agents (and connect as many entities) for the biggest simulation (50) and see that they do not go crazy if they don't get percepts for some time :)

This was brought up in the google forum, maybe a better idea than what we are doing now?

[link](https://groups.google.com/d/msg/agentcontest/xJ2mD3FOlC8/eP454MZCAgAJ)

**Comment by s1l3n0** [comment]
it looks like to be a pertinent solution. as agents are (should be)
reactive, it is better to create them and give them a "idle" script, if
creation and setup time could take some time.
still you need to create good mechanism for the "loading" script and
"entering in the arena" steps.

**Comment by DanielPerezJensen** [comment]
I tried this but I feel that we may as well use the first message we receive to determine the amount of agents we need, as we are doing now. Because making 50 threads and maintaning them for so long without any real use may be kinda superfluos and performance degrading. Thoughts?
