### ISSUE TITLE
Confusing usage of the word node

### ISSUE THREAD

**Issue by DanielPerezJensen** [DanielPerezJensen/mapc-uva#46]
There is still a confusing usage of the word node (and other things) in function names in graph.py. Such as:

```python
def get_local_nodes(self, agent_id, offset=None):
    pass
def get_local_agents(self, agent_id, team='A'):
    pass
```

These two functions for example don't actualy return a Node or Agent object but they return coordinates.

**Comment by dorian4840** [comment]
Only the documentation explains that the functions return the coordinates instead of the nodes or agents. I will change the function names to better represent their goal.
