### ISSUE TITLE
move _manhattan_distance(coords1, coords2)  from builder to agent

### ISSUE THREAD

**Issue by YassinAbdelrahman** [DanielPerezJensen/mapc-uva#51]
Could this function be moved from builder.py to agent.py? I think it is a basic function every role could use.

**Comment by DanielPerezJensen** [comment]
While this may be a good idea for this case if we allow each midly useful function to go into agent it may bloat it too much and move to far away from the idea we have about what exactly Agent is. Namely a dummy agent that can perform all primitive functions.

**Comment by YassinAbdelrahman** [comment]
Sounds fair, will just put it in the roles that need it.
